"""drop marketing consent and gdpr consent columns

Revision ID: 08e36f59fa48
Revises: fba51a7d9629
Create Date: 2026-07-31 11:39:37.746616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e36f59fa48'
down_revision: Union[str, None] = 'fba51a7d9629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'consent_at')
    op.drop_column('users', 'marketing_consent')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'privacy_policy_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privacy_policy_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('terms_accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('marketing_consent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('consent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
