"""add purpose column to otp

Revision ID: 2670c8f786f6
Revises: 78ddb521c493
Create Date: 2026-08-01 10:28:17.631305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2670c8f786f6'
down_revision: Union[str, None] = '78ddb521c493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('purpose', sa.String(), server_default='email_verification', nullable=False))
    op.create_index('ix_otp_user_id_purpose', 'otp', ['user_id', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_user_id_purpose', table_name='otp')
    op.drop_column('otp', 'purpose')
    # ### end Alembic commands ###
