"""align transcripts table with schema.dbml (key_insight, approved_at, created_at, drop overview, price to int)

Revision ID: 5ce9a2630de4
Revises: 4bfe6a1d36eb
Create Date: 2026-08-03 13:48:52.362547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ce9a2630de4'
down_revision: Union[str, None] = '4bfe6a1d36eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('key_insight', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('transcripts', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('transcripts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('transcripts', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('transcripts', 'overview')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('transcripts', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('transcripts', 'created_at')
    op.drop_column('transcripts', 'approved_at')
    op.drop_column('transcripts', 'key_insight')
    # ### end Alembic commands ###
