"""add authors, transcripts, entitlements

Revision ID: 78ddb521c493
Revises: 08e36f59fa48
Create Date: 2026-07-31 17:16:03.612284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ddb521c493'
down_revision: Union[str, None] = '08e36f59fa48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('final_transcript', sa.JSON(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_author_id'), 'transcripts', ['author_id'], unique=False)
    op.create_index('ix_transcripts_domain', 'transcripts', ['domain'], unique=False)
    op.create_index('ix_transcripts_geography', 'transcripts', ['geography'], unique=False)
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.create_index('ix_transcripts_is_active_published_at', 'transcripts', ['is_active', 'published_at'], unique=False)
    op.create_table('entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('source', sa.String(), server_default='purchase', nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'transcript_id', name='uq_entitlements_user_transcript')
    )
    op.create_index(op.f('ix_entitlements_id'), 'entitlements', ['id'], unique=False)
    op.create_index('ix_entitlements_order_item_id', 'entitlements', ['order_item_id'], unique=False)
    op.create_index('ix_entitlements_user_id_status', 'entitlements', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entitlements_user_id_status', table_name='entitlements')
    op.drop_index('ix_entitlements_order_item_id', table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index('ix_transcripts_is_active_published_at', table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_index('ix_transcripts_geography', table_name='transcripts')
    op.drop_index('ix_transcripts_domain', table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_author_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
