"""restructure users table for email encryption, merged otp, lockout, db-tracked reset

Revision ID: 8d658e484901
Revises: 2670c8f786f6
Create Date: 2026-08-03 00:12:58.462611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d658e484901'
down_revision: Union[str, None] = '2670c8f786f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # No backfill path exists for email_encrypted/email_hash (the encryption
    # key doesn't exist retroactively for old plaintext emails), and the new
    # email_encrypted/email_hash columns are NOT NULL - wipe dev data first so
    # the ALTER TABLE below doesn't fail against existing rows. entitlements
    # cascades from users; otp is dropped outright below regardless.
    op.execute("TRUNCATE TABLE users, entitlements RESTART IDENTITY CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_id'), table_name='otp')
    op.drop_index(op.f('ix_otp_user_id_expire_time'), table_name='otp')
    op.drop_index(op.f('ix_otp_user_id_purpose'), table_name='otp')
    op.drop_table('otp')
    op.add_column('users', sa.Column('email_encrypted', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('email_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expire_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('reset_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expire_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_requested_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'reset_requested_at')
    op.drop_column('users', 'reset_token_expire_at')
    op.drop_column('users', 'reset_token_hash')
    op.drop_column('users', 'otp_retry_count')
    op.drop_column('users', 'otp_expire_time')
    op.drop_column('users', 'otp_hash')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email_hash')
    op.drop_column('users', 'email_encrypted')
    op.create_table('otp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expire_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(), server_default=sa.text("'email_verification'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otp_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_pkey'))
    )
    op.create_index(op.f('ix_otp_user_id_purpose'), 'otp', ['user_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_otp_user_id_expire_time'), 'otp', ['user_id', 'expire_time'], unique=False)
    op.create_index(op.f('ix_otp_id'), 'otp', ['id'], unique=False)
    # ### end Alembic commands ###
