"""add carts and cart_items tables

Revision ID: 9e9d6ae7e372
Revises: 5ce9a2630de4
Create Date: 2026-08-03 17:23:19.418716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9d6ae7e372'
down_revision: Union[str, None] = '5ce9a2630de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_guest_id'), 'carts', ['guest_id'], unique=False)
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_index('ix_carts_user_id_status', 'carts', ['user_id', 'status'], unique=False)
    op.create_index('uq_carts_active_guest', 'carts', ['guest_id'], unique=True, postgresql_where=sa.text("status = 'active' AND guest_id IS NOT NULL"))
    op.create_index('uq_carts_active_user', 'carts', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active' AND user_id IS NOT NULL"))
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'transcript_id', name='uq_cart_items_cart_transcript')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('uq_carts_active_user', table_name='carts', postgresql_where=sa.text("status = 'active' AND user_id IS NOT NULL"))
    op.drop_index('uq_carts_active_guest', table_name='carts', postgresql_where=sa.text("status = 'active' AND guest_id IS NOT NULL"))
    op.drop_index('ix_carts_user_id_status', table_name='carts')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_guest_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
